feat(core): Addition of PadEfsStorage construct
aws/aws-rfdk pull request #365
Opened 2021-03-26 15:53 UTC by ddneilson

Implements: https://github.com/aws/aws-rfdk/issues/364

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-26 20:10 UTC, jericht requested changes
Just some minor comments, otherwise this looks really good!

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +   * @default Security group with full egress and no ingress will be automaticaally created for each Lambda.
```suggestion
   * @default Security group no egress or ingress will be automatically created for each Lambda.
```

Looks like we are setting `allowAllOutbound: false` in the default security group below

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +      Runtime: 'nodejs14.x',
Should we assert the `Timeout` here as well, like we do for the padFilesystem lambda?

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +      desiredPaddingGB: 200,
nit: Should we move the `desiredPaddingGB` to a variable and have the assertions reference the variable?
```
// GIVEN
const desiredPaddingGb = 200;

// WHEN
// Create PadEfsStorage

// THEN
// reference desiredPaddingGB in the assertions
```

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +    const sg = new SecurityGroup(stack, 'TestSG', {
nit: Seems like the security group should be under a `// GIVEN` "block"

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/deadline/lib/repository.ts
> +        path: '/PaddingFiles',
nit: Should we rename this path with an `RFDK` prefix? It would make it more obvious that the files in this path are created by RFDK.

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/deadline/test/repository.test.ts
> +  const isolatedSubnetIds = [ 'PublicSubnet1', 'PublicSubnet2' ];
nit: Should we rename the IDs to `IsolatedSubnet#` as well?

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +  var filename: string = await determineNextSequentialFilename(mountPoint);
```suggestion
  let filename: string = await determineNextSequentialFilename(mountPoint);
```

Same goes for other uses of `var` that can be block-scoped

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
> + * Invoke "du -sh -BM" on the given location, to determine the total size in MB stored
```suggestion
 * Invoke "du -sh -BMB" on the given location, to determine the total size in MB stored
```

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +  beforeEach(async () => {
Looks like we're using these `beforeEach` and `afterEach` functions for all of these `describe` blocks. Should we move these functions outside of the `describe` blocks (and the `tempDirectory` variable) so they only need to be defined once? Could also wrap all the `describe` blocks in one parent `describe` and put these functions in that parent scope

2021-03-26 20:10 UTC, jericht commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +});
```suggestion
});

```

Missing newline

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +   * @default Security group with full egress and no ingress will be automaticaally created for each Lambda.
Heh. Yup. Right you are!

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +      Runtime: 'nodejs14.x',
We could. I was less concerned about the precise timeout of this one. The other is writing a tonne of big files, so I wanted to make sure that there was an assertion that the timeout was maximal (900s).

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +      desiredPaddingGB: 200,
That's sensible.

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +    const sg = new SecurityGroup(stack, 'TestSG', {
Right you are!

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/lib/repository.ts
> +        path: '/PaddingFiles',
I like it. Good idea

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/test/repository.test.ts
> +  const isolatedSubnetIds = [ 'PublicSubnet1', 'PublicSubnet2' ];
Yes. That would be consistent. Whoops...

For the record. I had to change these 'cause you cannot create a Lambda in a public subnet without a particular option on the Lambda definition. Seemed silly to provide that option just for a test, and customers shouldn't be deploying their EFS with a public IP.

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
> + * Invoke "du -sh -BM" on the given location, to determine the total size in MB stored
Good attention to detail. I originally had the code as `-BM` but EFS seems to use MB units for billing, so I went for staying consistent.

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +  var filename: string = await determineNextSequentialFilename(mountPoint);
Good point!

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +  beforeEach(async () => {
I was going for grouping tests by top-level theme: "Filesystem mods", "getDiskUsage" handler, and "padFilesystem" handler. It *could* just all be under the same describe, or not use a describe at all, but I like the grouping. Makes my OCD a little happier. :-)

2021-03-31 03:31 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +});
Thanks!

2021-03-31 15:12 UTC, jusiskin requested changes
Overall this is great. Just a few suggestions here - great work!

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +  readonly desiredPaddingGB: number;
nit: we *could* use the [`Size`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Size.html) type that CDK provides here. This has methods that deal in the *bibytes family of units - which conveniently are the same family of units that [EFS uses for computing baseline throughput](https://docs.aws.amazon.com/efs/latest/ug/performance.html#efs-burst-credits):

> The baseline rate is 50 MiB/s per TiB of storage

It provides an expressive API for specifying storage sizes in Gibibytes and higher-order units and also is able to enforce that they be multiples of a particular unit (gibibytes in our case):

```ts
import { Size } from '@aws-cdk/core';

// ...
const size = Size.pebibyte(2);
const sizeInGiB = size.toGibibytes({ rounding: SizeRoundingBehavior.FAIL });
```

What do you think?

2021-03-31 15:12 UTC, jusiskin commented on examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
> +                permissions='744',
Was the intention to make this directory readable by all users mounting the EFS? If so, I believe we want to set this to `755`, which is required to enter the directory, list its contents, and access its files. Otherwise, we should simply set this to `750` or `700`.

Same feedback applies to the TS example and defaults in the `Repository` construct.

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +  protected static readonly MAX_GB_PER_CALL = 65;
as discussed offline, this is no longer used.

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/test/repository.test.ts
> +  expect(repo.node.tryFindChild('PadEfsStorage')).toBeDefined();
We should also assert the EFS access point for padding files is created here.

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/lib/repository.ts
> +          permissions: '744',
same feedback about using one of `755` / `750` / `700`

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
> +  const numericFiles = dirContents.filter(name => digitsRegex.test(name)).sort();
nit: the regex is not anchored, so it will match any string containing a single digit. I believe the intend was to match entirely numeric strings, which would be:

```ts
const digitsRegex = /^\d+$/;
```

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +}
It looks like errors are never surfaced to the caller here. I understand we want to be robust here and attempt to skip a file if we encounter errors and try deleting other files.

Can we change the code to throw an error at the end if we were unable to delete the desired number of files by the end of the loop? That way the state machine would actually show an error for this state and transition to the fail state.

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +  const duGB = Math.floor(await diskUsage(mountPoint) / FILESIZE);
Perhaps it is a variable naming issue (see my comment above), but I'm trying to figure out why `duGB` would be a function of the size of the files we create

2021-03-31 15:12 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +    }
I was a little bit confused about this expected result here (a single 10MB file) given we're passing in a `desiredPadding` of 1GB. The call in the `GIVEN` section appears to change the file size (10MB), but we only expect one of those 10MB files. It occurred to me that may have been by design to reduce storage requirements and reduce IO for running the tests.

Perhaps a comment above the file size expectation would help. What do you think?

2021-03-31 15:47 UTC, jericht commented on packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
> +      Runtime: 'nodejs14.x',
Sounds good to me

2021-03-31 15:47 UTC, jericht commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +  beforeEach(async () => {
Sure, works for me

2021-03-31 15:48 UTC, jericht submitted a review, later dismissed

2021-03-31 16:38 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
> +                permissions='744',
Changed to 700

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +  protected static readonly MAX_GB_PER_CALL = 65;
Yup. Nor `LAMBDA_DURATION` -- both removed.

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/lib/repository.ts
> +          permissions: '744',
Done

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/test/repository.test.ts
> +  expect(repo.node.tryFindChild('PadEfsStorage')).toBeDefined();
Good idea.

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
> +  const numericFiles = dirContents.filter(name => digitsRegex.test(name)).sort();
Good catch!

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +  const duGB = Math.floor(await diskUsage(mountPoint) / FILESIZE);
Renamed: `scaledUsage`

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +    }
Added a comment to the top of the test where we set `setDefaultFilesize(10)`

2021-03-31 16:38 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +  readonly desiredPaddingGB: number;
Great idea. Looking into it also surfaced that I had the units wrong. EFS is all on GiB rather than GB. So, I fixed that throughout as well.

2021-03-31 17:03 UTC, jericht submitted a review, later dismissed

2021-03-31 17:08 UTC, jusiskin commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> + * is no longer allowed to burst throughput and you will be limited in throughput to the greater of 1MB/s
nit: one leftover here? `1MB/s` &rarr; `1MiB/s`

2021-03-31 17:13 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> + * is no longer allowed to burst throughput and you will be limited in throughput to the greater of 1MB/s
Fixed.

2021-03-31 17:13 UTC, jusiskin commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> +  readonly desiredPaddingGB: number;
Looks great!

2021-03-31 17:14 UTC, jusiskin commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> + * is no longer allowed to burst throughput and you will be limited in throughput to the greater of 1MB/s
resolved

2021-03-31 17:14 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
> +    }
Much better - thanks!

2021-03-31 18:01 UTC, jericht commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> + * to burst again if it is able to acrue burst credits by staying below its baseline throughput for a time.
```suggestion
 * to burst again if it is able to accrue burst credits by staying below its baseline throughput for a time.
```

2021-03-31 18:04 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
> + * to burst again if it is able to acrue burst credits by staying below its baseline throughput for a time.
Fixed.

2021-03-31 18:05 UTC, jericht approved these changes

2021-03-31 18:22 UTC, jusiskin commented on packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
> +}
Resolved

2021-03-31 18:23 UTC, jusiskin approved these changes
Great job, Daniel! Approved

2021-03-31 18:24 UTC, merged