feat(integ): Added SSM Instance Policy Aspect
aws/aws-rfdk pull request #411
Opened 2021-05-05 20:28 UTC by charlesmjm

### Problem

The ```AmazonSSMManagedInstanceCore``` needs to be added to all instances launched by integration.

### Solution

Added an Aspect to add the ```AmazonSSMManagedInstanceCore``` to all Instances and ASG roles of an application. Implemented the Aspect in each of the integration apps.

### Testing

* Confirmed the ```AmazonSSMManagedInstanceCore``` policy is applied to all instances launched by an end-to-end test. 
* Confirmed that the end-to-end test completed successfully:

```
Complete!
Pretest setup runtime: 0m 1s
Infrastructure stack deploy runtime: 2m 53s
Infrastructure stack cleanup runtime: 2m 6s
Results for test component deadline_01_repository:
  -Tests ran: 21
  -Tests passed: 21
  -Tests failed: 0
  -Deploy runtime:     26m 28s
  -Test suite runtime: 0m 29s
  -Cleanup runtime:    12m 54s
Results for test component deadline_02_renderQueue:
  -Tests ran: 10
  -Tests passed: 10
  -Tests failed: 0
  -Deploy runtime:     25m 10s
  -Test suite runtime: 1m 5s
  -Cleanup runtime:    15m 22s
Results for test component deadline_03_workerFleetHttp:
  -Tests ran: 8
  -Tests passed: 8
  -Tests failed: 0
  -Deploy runtime:     56m 48s
  -Test suite runtime: 1m 50s
  -Cleanup runtime:    35m 25s
Results for test component deadline_04_workerFleetHttps:
  -Tests ran: 8
  -Tests passed: 8
  -Tests failed: 0
  -Deploy runtime:     59m 20s
  -Test suite runtime: 1m 56s
  -Cleanup runtime:    35m 32s
``` 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-05 22:01 UTC, jericht requested changes
Just a couple of tiny comments, but everything else looks good to me!

2021-05-05 22:01 UTC, jericht commented on integ/components/deadline/deadline_02_renderQueue/bin/deadline_02_renderQueue.ts
> +Aspects.of(app).add(new SSMInstancePolicyAspect());
nit: missing newline at the end of the file. Could add these newlines for the other files as well?

2021-05-05 22:01 UTC, jericht commented on integ/lib/ssm-policy-aspect.ts
> +  private static SSM_POLICY = ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMManagedInstanceCore');
```suggestion
  private static readonly SSM_POLICY = ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMManagedInstanceCore');
```

2021-05-05 22:09 UTC, jericht commented
Also, I think this commit should be a `chore` instead of `feat`, since it's not adding new functionality to the tests themselves. What do you think?

2021-05-06 16:26 UTC, charlesmjm commented on integ/components/deadline/deadline_02_renderQueue/bin/deadline_02_renderQueue.ts
> +Aspects.of(app).add(new SSMInstancePolicyAspect());
@jericht added new lines.

2021-05-06 16:26 UTC, charlesmjm commented on integ/lib/ssm-policy-aspect.ts
> +  private static SSM_POLICY = ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMManagedInstanceCore');
@jericht added readonly.

2021-05-06 17:05 UTC, jusiskin requested changes
Looks great, and thanks for the contribution, @charlesmjm!

Regarding the commit and PR title, I believe @jericht had meant using `chore` for the verb but keep `integ` for the category. Conventionally, we use present-tense for the description. Putting this together, how about this:

```
chore(integ): add SSMInstancePolicyAspect
```

2021-05-06 17:14 UTC, jericht approved these changes

2021-05-06 17:17 UTC, jericht requested changes
Looks like I missed that the actual commit message hasn't changed yet to something like @jusiskin's suggestion, just the PR title.

2021-05-06 17:23 UTC, charlesmjm commented
> Looks great, and thanks for the contribution, @charlesmjm!
> 
> Regarding the commit and PR title, I believe @jericht had meant using `chore` for the verb but keep `integ` for the category. Conventionally, we use present-tense for the description. Putting this together, how about this:
> 
> ```
> chore(integ): add SSMInstancePolicyAspect
> ```

Fixed Commit and PR titles.

2021-05-06 17:31 UTC, jusiskin approved these changes

2021-05-06 18:05 UTC, jericht approved these changes

2021-05-06 18:31 UTC, merged