chore(deps): bumping cdk from 1.99.0 to 1.102.0
aws/aws-rfdk pull request #415
Opened 2021-05-10 20:49 UTC by jusiskin

Bumps CDK version from 1.96.0 to 1.99.0

## Notes

*   CDK upgraded `eslint-plugin-jest` from `24.3.4` &rarr; [`24.3.6`](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v24.3.6).
    *   fixed a bug in the `no-conditional-expect` rule. RFDK tests that had an `expect(...)` statement within a condition branch were emitting errors
        *   Tests were refactored so that expects were not conditional
    *   some tests with the same name within a common scope (e.g. `describe` block) were also being flagged
        *   Tests were refactored to have  unique names

## Testing

*   Ran `yarn build` from the root which performs a basic RFDK TypeScript build and runs our regression test suite. All tests passed
*   Deployed the `All-In-AWS-Infrastructure-Basic` example app successfully

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-10 22:12 UTC, ddneilson requested changes

2021-05-10 22:12 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-SEP/ts/bin/config.ts
> +  public readonly deadlineClientLinuxAmiMap: Record<string, string> = {['us-west-2']: 'aami-0c8431fc72742c110'};
```suggestion
  public readonly deadlineClientLinuxAmiMap: Record<string, string> = {['us-west-2']: 'ami-0c8431fc72742c110'};
```

2021-05-11 01:01 UTC, kozlove-aws approved these changes

2021-05-11 14:00 UTC, ddneilson approved these changes

2021-05-11 14:34 UTC, merged