fix(deadline): fix issue in client TLS configuration for Deadline 10.1.18.5
aws/aws-rfdk pull request #543
Opened 2021-08-24 18:03 UTC by horsmand

I applied a fix to [this draft PR](https://github.com/aws/aws-rfdk/pull/537) to get the integ tests to pass, so I've created a new PR from my fork.

## Problem

The behavior of the `ChangeRepository[SkipValidation]` Deadline command in 10.1.18.5 has changed. It now clears the `ProxySSLCA` setting in `deadline.ini` before attempting to apply/validate the configuration. RFDK relied on the previous behavior where the `ProxySSLCA` was left unchanged.

## Solution

We cannot use `ChangeRepository` without supplying a "client certificate" since this will disable TLS. Instead, we have switched from using `ChangeRepository` to instead use `SetIniFileSetting ProxyRoot <RQ_ENDPOINT>` .  RFDK also relied on having `ChangeRepository` validate the connection and error if the connection settings were incorrect. We now change that validation to instead run a separate Deadline command to test the connection.

We made the same change to the Deadline configuration script that runs on the RFDK integ tests.

## Testing

The RFDK integ tests are now passing using the Deadline Client 10.1.18.5 to stage the Docker recipes and the `Deadline Worker Base Image Windows 10.1.18.5 2021-07-30T215517Z - ami-0d5da435a9d85896b` AMI for the worker fleets. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-24 19:02 UTC, jericht requested changes

2021-08-24 19:02 UTC, jericht commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            if change_repo_results.startswith('Deadline configuration error:'):
Are we certain that errors in connecting to the repository with always start with this string? Is it possible to capture the exit code of `ChangeRepository` and check that instead?

2021-08-25 19:32 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            if change_repo_results.startswith('Deadline configuration error:'):
I guess this can be removed now. Error checking was added on line 220.

2021-08-26 18:37 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            if change_repo_results.startswith('Deadline configuration error:'):
I performed a test using Deadline 10.1.18.5 without the fix applied so I could be sure that I'd be failing to run the Deadline Command. The log shows that it threw the `ValueError` exception when checking `proc.returncode` and never made it to the line to check if the result started with `Deadline configuration error:`, so I went ahead and removed this check.

2021-08-26 18:39 UTC, jericht commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            if change_repo_results.startswith('Deadline configuration error:'):
Great, thanks!

2021-08-26 18:39 UTC, jericht submitted a review, later dismissed

2021-08-27 14:42 UTC, ddneilson requested changes

2021-08-27 14:42 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            except Exception as e:
We should rethrow here, no? Else, if there's a connection error the log will look like:
```
Deadline connection error: ...
Deadline connection configured correctly
```
and this function will exit normally. This results in the script returning a 'success' return code whereas previously this function would throw an exception on error and result in the script returning an 'error' return code.

2021-08-27 14:42 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            change_repo_results = call_deadline_command(repo_args)
Just making 100% sure... you've verified that ChangeRepository returns a non-zero return code from deadlinecommand when it fails to connect to the repo? (i.e. when the settings are incorrect)?

2021-08-27 17:27 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            change_repo_results = call_deadline_command(repo_args)
Since the `proc.returncode` check was only added to the `call_deadline_command` in this commit, and the `ChangeRepository` command is also moved to only be called in the case where a client cert is applied (which isn't a valid use case in RFDK right now), I don't see why this should be a concern.

That said, I did kind of verify this by using Deadline 10.1.18.5 without the fix applied so that the `ChangeRepository` command would fail and the `call_deadline_command` should throw the `ValueError` exception when checking `proc.returncode`.

2021-08-27 17:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
> +            except Exception as e:
Yeah you're right. I tested this by setting the RCS endpoint to 'test' and then deployed with and without the `try/except`. It failed to deploy both times, but with the `try/except` in place, the logs did say that the connection was configured correctly when it wasn't.

I removed it.

2021-08-27 20:16 UTC, ddneilson approved these changes

2021-08-27 22:18 UTC, jericht approved these changes

2021-08-27 22:19 UTC, merged