test(integ): add test suites WF-1, WF-2 for worker fleet instance fun…
aws/aws-rfdk pull request #57
Opened 2020-08-13 14:42 UTC by aws-painec

…ctional tests (Linux workers, http and https modes)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-08-13 20:54 UTC, grbartel requested changes

2020-08-14 13:21 UTC, grbartel requested changes
Did you miss including the powershell scripts for the windows tests?  Or do they use the bash scripts also?

2020-08-18 15:12 UTC, grbartel approved these changes
This is looking good.  Thanks for all the hard work

2020-08-19 17:41 UTC, ddneilson approved these changes
Thanks for the contribution, Claire. This is great stuff!

2020-08-19 17:42 UTC, merged