chore(deadline): added tests for configure_identity_registration_settings.py
aws/aws-rfdk pull request #593
Opened 2021-10-04 16:49 UTC by horsmand

1. Wrote a bash script to execute the python unit tests and added a script entry in `package.json` called `testpy` to run the bash script. The tests are really lightweight, so I expanded the `test` target to run them along with the other CDK unit tests.
2. Wrote unit tests for `configure_identity_registration_settings.py`. I think coverage is pretty good but likely not 100%
3. Updated `_camel_to_snake_case()`  because the old version didn't cover some conversions properly.
4. Fixed 2 small bugs found with the unit tests for using a Secret from file. Not sure if we should bother supporting this feature though.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-04 20:34 UTC, jusiskin requested changes
This looks great overall. I just have a few minor suggestions - mostly around improving readability of the tests.

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/.gitignore
> +__pycache__/
I moved this to `packages/aws-rfdk/.gitignore` in #576, so we can remove this file here.

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/test-python.sh
> +set -eou pipefail
nit: I had thought this needed to be:

```suggestion
set -euo pipefail
```

since the `pipefail` is an arg to the `-o` command-line option of `set`.

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +#!/usr/bin/env python3
nit: since we're introducing the test path convention here, what do you think about moving this file into a `test` sub-directory to keep them separate?

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +        ])
So we expect `delete_removed_settings` to remove `REG_SETTING_RFDK_2` here which uses both `subnet-bbbbbbb` (connection subnet) and `subnet-2222222` (source subnet).

`subject.delete_removed_settings` will remove this setting because `subnet-2222222` is not included in `source_subnets`. The test code/comments do not mention this subnet, so it is not quite obvious why the behavior is expected.

Perhaps we need a comment above the assertion that explains this, or is there a way we can make this test easier to follow?

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +}
nit: could these be made into their named tuple literal equiavlents?

```suggestion
REG_SETTING_RFDK_1 = subject.LoadBalancerIdentityRegistrationSetting(
    connection_ip_filter_type=0,
    connection_ip_filter_value="111.111.*.*", # 111.111.0.0/16
    source_ip_filter_type=0,
    source_ip_filter_value="123.123.123.*", # 123.123.123.0/24
    settings_id="settings1",
    settings_name="RfdkSubnet|subnet-aaaaaaa|subnet-1111111",
    is_dnabled=True,
    default_status=2,
    default_role="Client"
)
```

this de-couples the tests from the `LoadBalancerIdentityRegistrationSetting.from_json(...)`. Same feedback applies to other places in this file

2021-10-04 20:34 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +        })
What do you think about sourcing the values for some of these expected fields from literals to using attributes of `REG_SETTINGS_RFDK_1` where applicable? just to help depict what fields we expect to be updated vs what we expect to remain unchanged?

2021-10-06 21:30 UTC, kozlove-aws submitted a review, later dismissed
LGTM! Good job.

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +        })
Updated

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +}
Updated

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +        ])
Updated to explain better.

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +#!/usr/bin/env python3
Moved.

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/test-python.sh
> +set -eou pipefail
Oh yeah, my mistake.

2021-10-08 04:31 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/.gitignore
> +__pycache__/
Removed.

2021-10-08 15:43 UTC, kozlove-aws submitted a review, later dismissed

2021-10-08 17:06 UTC, jusiskin requested changes
Looking good. I have a few readability suggestions, which I've provided code for, but there's still some missing coverage around negative tests that we may want to add.

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +sys.path.remove(str(_parentdir))
This can be simplified to:

```suggestion
import configure_identity_registration_settings as subject
```

but you need to make a few changes:

1.  Modify the `-s` to be up a directory in `packages/aws-rfdk/test-python.sh`:

    ```sh
    python3 -m unittest discover -s "$PWD/lib/deadline/scripts/python" -b
    ```
2.  Add an empty `packages/aws-rfdk/lib/deadline/scripts/python/test/__init__.py` file to mark the `test` directory as a python package

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        )
should we assert the arguments that `self.dl_secrets_run_json` was called with?

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +    def test_create(self):
while this covers one situation where we **want to** create a setting, should we have negative test for when we **should not** create a setting?

same applies for update and delete

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        )
I'm wondering if we can write this in a way that makes the intent a little more clear. While the above code is logically equivalent, how about this:

```suggestion
        expected = subject.LoadBalancerIdentityRegistrationSetting(
            # We expect RFDK_REG_SETTING_1 to be updated
            settings_id                 = RFDK_REG_SETTING_1.settings_id,
            # The values we expect to be applied
            connection_ip_filter_type   = "IPv4Match",
            connection_ip_filter_value  = subject.cidr_to_ipv4_match(subnet_to_cidr[connection_subnet_ids[0]]),
            source_ip_filter_type       = "IPv4Match",
            source_ip_filter_value      = subject.cidr_to_ipv4_match(subnet_to_cidr[source_subnets[0].subnet_id]),
            settings_name               = RFDK_REG_SETTING_1.settings_name,
            is_enabled                  = True,
            default_status              = source_subnets[0].registration_status,
            default_role                = source_subnets[0].role
        )
```

Do you think this makes it any more clear when reading the code that we expect the setting values to be updated using the values from `connection_subnet_ids`, `subnet_to_cidr`, and `source_subnets` rather than from the previous values?

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        self.assertEqual(self.dl_secrets.run_str.call_count, 4)
We can use [`Mock.assert_any_call(...)`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_any_call) to search all calls to the mock.

```suggestion
        for connection_subnet_id in connection_subnet_ids:
            for source_subnet in source_subnets:
                expected = subject.LoadBalancerIdentityRegistrationSetting(
                    connection_ip_filter_type  = "IPv4Match",
                    connection_ip_filter_value = subject.cidr_to_ipv4_match(subnet_to_cidr[connection_subnet_id]),
                    source_ip_filter_type      = "IPv4Match",
                    source_ip_filter_value     = subject.cidr_to_ipv4_match(subnet_to_cidr[source_subnet.subnet_id]),
                    settings_id                = '', # Unused
                    settings_name              = f"RfdkSubnet|{connection_subnet_id}|{source_subnet.subnet_id}",
                    is_enabled                 = True,
                    default_status             = source_subnet.registration_status,
                    default_role               = source_subnet.role
                )
                self.dl_secrets.run_str.assert_any_call(
                    "CreateLoadBalancerIdentityRegistrationSetting",
                    expected.settings_name,
                    expected.connection_ip_filter_type,
                    expected.connection_ip_filter_value,
                    expected.source_ip_filter_type,
                    expected.source_ip_filter_value,
                    expected.default_role,
                    expected.default_status,
                    str(expected.is_enabled)
                )
```

2021-10-08 17:06 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        })
How about:

```suggestion
        expected = subject.LoadBalancerIdentityRegistrationSetting(
            connection_ip_filter_type   = "IPv4Match",
            connection_ip_filter_value  = subject.cidr_to_ipv4_match(subnet_to_cidr[connection_subnet_ids[0]]),
            source_ip_filter_type       = "IPv4Match",
            source_ip_filter_value      = subject.cidr_to_ipv4_match(subnet_to_cidr[source_subnets[0].subnet_id]),
            settings_id                 = "", # Ignored
            settings_name               = f"RfdkSubnet|{connection_subnet_ids[0]}|{source_subnets[0].subnet_id}",
            is_enabled                  = True,
            default_status              = source_subnets[0].registration_status,
            default_role                = source_subnets[0].role
        )
```

we already have separate testing for cidr_to_ipv4_match so this should be okay and helps illustrate the expected behavior.

What do you think?

2021-10-08 17:11 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test_configure_identity_registration_settings.py
> +}
I'd overlooked the fact that `get_rfdk_registration_settings` gets JSON-encoded settings from `deadlinecommand` and passes that to `LoadBalancerIdentityRegistrationSetting.from_json`. This makes testing tricky since we either need to mock `deadlinecommand` to return valid JSON, or mock `LoadBalancerIdentityRegistrationSetting.from_json` to have stateful returns.

Either is not ideal, but I think it suffices for now and if we ever need to, we can refactor that later. Resolving.

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +sys.path.remove(str(_parentdir))
Well that was some python wizardry I didn't know about. Thanks!

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        )
Sure, updated

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +    def test_create(self):
I've added some tests for these cases.

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        )
Yeah this makes sense to me. I was a bit wary about using the `cidr_to_ipv4_match` to do the conversion, but that method is tested elsewhere so it should be fine. Do you see any reason not to take the filter types from `RFDK_REG_SETTING_1` as well?

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        self.assertEqual(self.dl_secrets.run_str.call_count, 4)
Ah thanks, not sure how I missed that method.

2021-10-08 18:50 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +        })
Updated

2021-10-08 19:39 UTC, jusiskin requested changes
Just one minor method name conflict. But otherwise this is great

2021-10-08 19:39 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +    def test_create_and_update_no_connection_subnets(self):
```suggestion
    def test_create_and_update_no_source_subnets(self):
```

2021-10-08 19:54 UTC, horsmand commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +    def test_create_and_update_no_connection_subnets(self):
Whoops, surprised it let me create methods with the same name. Fixed.

2021-10-08 20:02 UTC, jusiskin commented on packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
> +    def test_create_and_update_no_connection_subnets(self):
Technically it's valid python, but it could be caught with a linter. That's out of scope for this work, so we can add it to the backlog

2021-10-08 20:03 UTC, jusiskin approved these changes
Great work here! This looks good to me

2021-10-08 20:13 UTC, kozlove-aws approved these changes

2021-10-08 20:20 UTC, merged