feat(integ): add secrets management identity registration settings tests
aws/aws-rfdk pull request #596
Opened 2021-10-07 02:38 UTC by jericht

### Notes
- Adds integration tests for the Secrets Management identity registration settings feature implemented in https://github.com/aws/aws-rfdk/pull/576
    - The `deadline_05_secretsManagement` test suite now uses a default (dummy) UBL certificate secret (create if not found). This secret is meant to be created once per account + region these integ tests are run in and referenced in all future integ tests, since its content is static (basically empty).
- Adds a new developer mode to the integration test script so that the CF stacks will not be torn down, and making the bastion host accessible via SSM, making it easier to iterate on integ test development
- Reorganizes the `NetworkTier` to have dedicated subnet configurations for each Deadline component (RQ ALB, workers, license forwarder, etc.)
- Adds options to the `RenderStruct` construct to setup a `UsageBasedLicensing` construct. This is currently only used in the `deadline_05_secretsManagement` test suite.
- Adds a new `SepWorkerStruct` that configures the Spot Event Plugin via `ConfigureSpotEventPlugin` construct

~~**Note for reviewers:** This is based off of the changes in https://github.com/aws/aws-rfdk/pull/576. It will be easier to review by looking at the commits authored by me so only my changes are shown in the file diffs.~~

### Testing
Took the following steps to test:
- Staged Deadline 10.1.18 Docker recipes & updated them with the changes for the Secrets Management feature
- Changed the `SecretsManagementIdentityRegistration` construct to use a version of Deadline Client with the Secrets Management changes
- Let the integ test create a dummy secret for the UBL certificates, then ran the integration tests and verified they passed
- Ran all the integ test suites and verified they passed

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-07 14:15 UTC, horsmand commented
This commit just got merged to the feature branch so we'll need to rebase on it and set the credentials removal policy to `DESTROY` https://github.com/aws/aws-rfdk/commit/d0241d6989b1af1fbced953ed91444946b2655f8#diff-299db76f4b1d275d1140f5b68b75b5954a2c54ef4f6770dfc410bb21668aea8eR318

2021-10-07 15:14 UTC, horsmand requested changes
Overall this looks good, I really like that you fixed up the `--deploy-and-test-only` flag by adding the `DEV_MODE` env var. The only part I'm unsure about is the intention of adding UBL and whether it's actually optional given how it's currently written.

2021-10-07 15:14 UTC, horsmand commented on integ/components/_infrastructure/lib/network-tier.ts
> +export enum NetworkTierSubnets {
Do we need this enum? I don't see it referenced anywhere other than in the type right below it and we could just list the subnets there.

2021-10-07 15:14 UTC, horsmand commented on integ/components/_infrastructure/lib/network-tier.ts
> +export type NetworkTierSubnetConfiguration = {
What was the reasoning to use a `type` over an `interface` here? I'm not sure how this plays with JSII. That probably doesn't matter since I'm quite sure we never transpile this integ package, but it's probably best if we follow the typescript restrictions everywhere in our repository for consistency. 

From https://aws.github.io/jsii/user-guides/lib-author/typescript-restrictions/#interfaces:
> The jsii type model distinguishes two kinds of interfaces:
>
> * Behavioral interfaces, which can declare methods and properties
> * Structs, which are immutable pure data entities, and can consequently only declare readonly properties
>
> A name convention is used to distinguish between these two: behavioral interfaces must have a name that starts with a I prefix, while structs must not have such a prefix.

I don't see why we can't use the struct interface here.

2021-10-07 15:14 UTC, horsmand commented on integ/scripts/bash/rfdk-integ-e2e.sh
> +  if [[ "$DEV_MODE" == "true" ]]; then
I can't seem to comment on lines that aren't modified in this commit, but above this on line 88 there's a check that is broken. It currently has:
```
# If executing worker fleet tests, find Deadline AMIs based on supplied version
if [ ! "${SKIP_deadline_03_repository_TEST-}" = true ]; then
    source $BASH_SCRIPTS/fetch-worker-amis.sh
fi
```
I think we want to make sure we're not skipping `deadline_03_workerFleetHttp`, `deadline_03_workerFleetHttps`, and `deadline_05_secretsManagement`. I almost wonder if the check is worth doing since it's easy to get missed when we make modifications and fetching AMIs likely isn't too expensive.

2021-10-07 15:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +  }
Should this return undefined rather than throw an error? I don't see how these tests work without having the UBL env vars defined, but the documentation says it should be possible.

2021-10-07 15:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +  readonly sepWorkerStruct?: SepWorkerStruct;
These don't seem optional

2021-10-07 15:14 UTC, horsmand commented on integ/test-config.sh
> +export UBL_CERTIFICATE_BUNDLE_SECRET_ARN
How is this intended to be used? Will UBL be used in our canaries or pipelines?

2021-10-07 15:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +    props.sepWorkerStruct?.fleets.forEach(f => this.testInstance.connections.allowTo(f, Port.tcp(22)));
What is the test instance connecting to these fleets for?

2021-10-07 15:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +   * Generates CfnOutputs for the Render Queue ALB subnets and Deadline client components.
```suggestion
   * Generates CfnOutputs for the Render Queue ALB subnets and Deadline client subnets.
```

2021-10-07 15:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/test/deadline_05_secretsManagement.test.ts
> +  if (!ublSubnetIds[testSuiteId]) {
Isn't UBL optional?

2021-10-07 20:01 UTC, jericht commented on integ/components/_infrastructure/lib/network-tier.ts
> +export enum NetworkTierSubnets {
We don't. I originally thought it would be needed but turned out it wasn't used, so I've removed it

2021-10-07 20:01 UTC, jericht commented on integ/components/_infrastructure/lib/network-tier.ts
> +export type NetworkTierSubnetConfiguration = {
Changed to a struct interface

2021-10-07 20:01 UTC, jericht commented on integ/test-config.sh
> +export UBL_CERTIFICATE_BUNDLE_SECRET_ARN
Sorry, forgot to put a comment here. Originally, I intended for this to be required when running the Secrets Management tests, but it makes more sense to make them optional overrides and have default behavior (e.g. upload dummy secret and use dummy license limits). I've added a comment here as well as implemented the default behavior.

2021-10-07 20:01 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +  }
I changed this to create a default dummy secret for UBL when this in not defined

2021-10-07 20:01 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +  readonly sepWorkerStruct?: SepWorkerStruct;
These are actually not needed, removed

2021-10-07 20:01 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +    props.sepWorkerStruct?.fleets.forEach(f => this.testInstance.connections.allowTo(f, Port.tcp(22)));
It's not, I forgot to remove this. Removed

2021-10-07 20:01 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
> +   * Generates CfnOutputs for the Render Queue ALB subnets and Deadline client components.
Updated

2021-10-07 20:01 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/test/deadline_05_secretsManagement.test.ts
> +  if (!ublSubnetIds[testSuiteId]) {
I've changed the UBL stuff to always get setup. This way our SM integ tests always have the same coverage, regardless of whether UBL certs were provided or not.

2021-10-07 20:01 UTC, jericht commented on integ/scripts/bash/rfdk-integ-e2e.sh
> +  if [[ "$DEV_MODE" == "true" ]]; then
Yeah I agree, I've removed that if condition.

2021-10-08 05:08 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/test/deadline_05_secretsManagement.test.ts
> +    const rqAlbSubnetIds = renderQueueAlbSubnetIds[testSuiteId];
I'm a little confused by the use of arrays and this `testSuiteId` in this file. I don't see the value of `testSuiteId` changing anywhere.

2021-10-08 05:08 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +    const archive = archiver('zip');
It looks like we've added a new dependency just to create this empty zip file. Why not just keep an empty zip file in our repo that we can use? Binary files in a git repo are generally bad, but I feel like this might warrant an exception since the file size is negligible. What do you think?

2021-10-08 05:09 UTC, horsmand commented
I forgot to mention that my last review was based on this diff, which covers the 2 latest commits: https://github.com/aws/aws-rfdk/pull/596/files/4bb8df5b36d32f0c435466b64cf21231950086d9..0a58b66e61cdca280e35e2d907b099ce7f485956

2021-10-08 16:23 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/test/deadline_05_secretsManagement.test.ts
> +    const rqAlbSubnetIds = renderQueueAlbSubnetIds[testSuiteId];
Good point. Unlike the other component tests, this test only has one test suite, I've removed this.

2021-10-08 16:23 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +    const archive = archiver('zip');
Good point! I think having the static empty file is much cleaner, updated.

2021-10-08 19:20 UTC, kozlove-aws reviewed
Looks good, just a couple tiny things.

2021-10-08 19:20 UTC, kozlove-aws commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +      const limit = parsedUblLicenseMap[l] > 0 ? parsedUblLicenseMap[l] : UsageBasedLicense.UNLIMITED;
if we expect here zero or negative values could be worth to validate if value more then `UsageBasedLicense.UNLIMITED`

2021-10-08 19:20 UTC, kozlove-aws commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +    } catch (e) {
How can we be sure that the only possible error is when the secret is not found? 
Could we check error type here?

2021-10-08 20:10 UTC, horsmand requested changes
We're very close! Just one comment for clarification.

2021-10-08 20:10 UTC, horsmand commented on integ/lib/storage-struct.ts
> +    const deadlineEfs = new FileSystem(this, 'FileSystem', {
Let's add a comment about why we need to create this all the time now but not the DocDB

2021-10-08 20:14 UTC, horsmand commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +      const limit = parsedUblLicenseMap[l] > 0 ? parsedUblLicenseMap[l] : UsageBasedLicense.UNLIMITED;
I know I saw it explained somewhere else in this PR, but maybe we can just add a comment here to say that anything that isn't a positive integer will be treated as unlimited.

2021-10-08 20:37 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +      const limit = parsedUblLicenseMap[l] > 0 ? parsedUblLicenseMap[l] : UsageBasedLicense.UNLIMITED;
Good call out! I think we can leave this as is though. Technically, there is no upper limit on the license count limit (see our [license-forwarder recipe documentation for UBL_LIMITS](https://gallery.ecr.aws/aws-thinkbox/deadline/license-forwarder)), and if there is a max value in Deadline, I think we can let Deadline enforce that. How does that sound?

2021-10-08 20:41 UTC, jericht commented on integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
> +    } catch (e) {
Good idea, added a check to make sure we get the `ResourceNotFoundException` error code

2021-10-08 20:42 UTC, jericht commented on integ/lib/storage-struct.ts
> +    const deadlineEfs = new FileSystem(this, 'FileSystem', {
Sure, added a little comment here as well as over the relevant `vpcSubnets` field

2021-10-08 20:44 UTC, jericht commented on integ/lib/storage-struct.ts
> +    const deadlineEfs = new FileSystem(this, 'FileSystem', {
Also just to make sure we're on the same page here, we can't make the DocDB all the time since the `StorageStruct` switches the type of database it uses based on the props it's given (see the `if` statements below this code), but it does not switch the filesystem type, which is why I have refactored it out.

Previous behavior of filesystem creation w.r.t the `databaseType` prop was:
- `DatabaseType.DocDB` => Create EFS and pass it into the `Repository`
- `DatabaseType.MongoDB` => Let `Repository` create the EFS
- `undefined` => Also let `Repository` create the EFS

I found it strange that we only created the EFS in the DocDB case since those two things aren't really tied to each other for our integ tests. Since I needed something other than the default EFS created by our `Repository`, I decided to just refactor the EFS creation outside of the database creation branches.

2021-10-08 20:50 UTC, jericht commented
@kozlove-aws @horsmand This is ready for re-review. Please don't merge if both of you approve, I'm going to do a final run of the integ test and merge it myself once it passes.

2021-10-08 21:13 UTC, horsmand reviewed
Ready to approve after we confirm the latest run of the tests pass.

2021-10-08 21:23 UTC, kozlove-aws approved these changes

2021-10-08 23:09 UTC, jericht commented
@horsmand The tests just passed, this is good to go

2021-10-11 16:54 UTC, horsmand approved these changes

2021-10-11 16:55 UTC, merged