feat(examples): use dedicated subnets in All-In-AWS-Infrastructure-Basic example
aws/aws-rfdk pull request #598
Opened 2021-10-07 17:43 UTC by jusiskin

## Summary

In #576, RFDK was modified to automatically configure Deadline Secrets Management identity registration settings based on the subnets used by RFDK Deadline constructs. This sets up the rules with least-privilege such that the farm will always function, but in order to further scope-down the identity registration settings rules, RFDK users should deploy RFDK Deadline constructs into their own dedicated subnets.

This PR modifies the `All-In-AWS-Infrastructure-Basic` example CDK applications to use dedicated subnets as we now recommend in our documentation.

Updated the Deadline `README.md` to point to the example for a reference implementation.

## Testing

Built and deployed Python and TypeScript example apps and verified that:

*   Python
    *  All instances are deployed in the proper subnets
    *  The Render Queue ALB is deployed in its own dedicated subnets
    *  RFDK creates Deadline Secrets Management identity registration settings for only the subnets involved
    *  End-to-end UBL render using SM succeeds
*   TypeScript
    *  All instances are deployed in the proper subnets
    *  The Render Queue ALB is deployed in its own dedicated subnets
    *  RFDK creates Deadline Secrets Management identity registration settings for only the subnets involved
    *  End-to-end UBL render using SM succeeds

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-07 19:21 UTC, horsmand requested changes
Did a quick pass. Looks good!

2021-10-07 19:21 UTC, horsmand commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
>      this.renderQueue = new RenderQueue(this, 'RenderQueue', {
This is missing setting the ALB subnets.

2021-10-07 20:10 UTC, jusiskin commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
>      this.renderQueue = new RenderQueue(this, 'RenderQueue', {
Good catch. Fixed this now

2021-10-07 22:47 UTC, jericht submitted a review, later dismissed
Looks good!

2021-10-08 18:52 UTC, horsmand approved these changes

2021-10-08 19:19 UTC, jericht approved these changes

2021-10-08 19:45 UTC, merged