chore(deps): bumping cdk from 1.116.0 to 1.129.0
aws/aws-rfdk pull request #618
Opened 2021-10-21 18:43 UTC by horsmand

Upgraded all our dependencies to prep for our next RFDK release.

Testing was done by running the build in the base directory along with all the typescript example directories, and deploying the basic example. I also upgraded JSII in our pipeline and deployed a test pipeline that ran against these changes.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-21 19:54 UTC, ddneilson requested changes
Looks like there's a whole pile of additional dependencies to sort through -- they added a bunch in the last 12 versions of CDK, or something, it seems.

From the CI:
```
aws-rfdk: $ cdk-build
aws-rfdk: warning JSII6: A "peerDependency" on "@aws-cdk/assets" at "1.128.0" means you should take a "devDependency" on "@aws-cdk/assets" at "1.128.0" (found "undefined")"
aws-rfdk: warning JSII6: A "peerDependency" on "@aws-cdk/aws-apigateway" at "1.128.0" means you should take a "devDependency" on "@aws-cdk/aws-apigateway" at "1.128.0" (found "undefined")"
aws-rfdk: warning JSII6: A "peerDependency" on "@aws-cdk/aws-apigatewayv2" at "1.128.0" means you should take a "devDependency" on "@aws-cdk/aws-apigatewayv2" at "1.128.0" (found "undefined")"
... and so on
```

2021-10-21 19:54 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
> +const network = new NetworkTier(app, 'NetworkTier1', { env });
How come we're changing the names of these?

2021-10-21 19:54 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
> +cdk.Aspects.of(app).add(new SSMInstancePolicyAspect());
Is this a left-over from testing?

2021-10-21 19:54 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
> +  public readonly acceptAwsThinkboxEula: AwsThinkboxEulaAcceptance = AwsThinkboxEulaAcceptance.USER_ACCEPTS_AWS_THINKBOX_EULA;
Leftover from testing. This needs to be 'REJECTS' by default -- legal requirement.

2021-10-21 19:54 UTC, ddneilson commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
> +  Stage,
This line & the next. Left-overs from testing?

2021-10-21 19:54 UTC, ddneilson commented on packages/aws-rfdk/lib/core/test/asset-constants.ts
> +  Bucket: stringLike('AssetParameters*S3BucketD97C6FDA'),
Huh. Any idea why this changed? afaik, CDK tries to guarantee stuff like this remains constant

2021-10-21 20:41 UTC, horsmand commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
> +const network = new NetworkTier(app, 'NetworkTier1', { env });
Crap, I had changes meant to be kept locally for testing that I accidentally added to the commit when I needed to rebase on the new changes from mainline.

2021-10-21 21:01 UTC, horsmand commented on packages/aws-rfdk/lib/core/test/asset-constants.ts
> +  Bucket: stringLike('AssetParameters*S3BucketD97C6FDA'),
Not sure why this would have changed, or only this one.

2021-10-21 21:02 UTC, horsmand commented
I've removed my test code but am still looking into why all those `warning JSII6` lines appeared in the build output.

2021-10-21 22:04 UTC, jusiskin commented on packages/aws-rfdk/lib/core/test/asset-constants.ts
> +  Bucket: stringLike('AssetParameters*S3BucketD97C6FDA'),
I wonder if it relates to this change included in CDK https://github.com/aws/aws-cdk/pull/16945 which shipped in CDK v1.128.0.

Perhaps this asset hash was baked from a Windows machine.

2021-10-21 22:40 UTC, jusiskin requested changes
Other than the feedback already brought up by @ddneilson, this looks good. Two small things with code suggestions here:

2021-10-21 22:40 UTC, jusiskin commented on tools/cdk-build-tools/package.json
> +    "@typescript-eslint/parser": "^4.3.0",
I believe this should be `^4.33.0` based on:

https://github.com/aws/aws-cdk/blob/v1.128.0/tools/%40aws-cdk/cdk-build-tools/package.json#L46

```suggestion
    "@typescript-eslint/parser": "^4.33.0",
```

2021-10-21 22:40 UTC, jusiskin commented on packages/aws-rfdk/package.json
> +    "@types/jest": "^27.0.2",
This should probably match the version of jest we're using in `cdk-build-tools` (`"^26.0.24"`) so that development type declarations match the jest library version being used to run tests.

```suggestion
    "@types/jest": "^26.0.24",
```

What do you think?

2021-10-22 15:44 UTC, horsmand commented on packages/aws-rfdk/package.json
> +    "@types/jest": "^27.0.2",
I updated this to match all the jest dependencies with those found in the `cdk-build-tools` .

2021-10-22 15:44 UTC, horsmand commented on tools/cdk-build-tools/package.json
> +    "@typescript-eslint/parser": "^4.3.0",
Fixed

2021-10-22 15:45 UTC, horsmand commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
> +const network = new NetworkTier(app, 'NetworkTier1', { env });
Fixed

2021-10-22 15:45 UTC, horsmand commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
> +cdk.Aspects.of(app).add(new SSMInstancePolicyAspect());
Removed

2021-10-22 15:45 UTC, horsmand commented on examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
> +  Stage,
Removed

2021-10-22 16:48 UTC, jusiskin commented on packages/aws-rfdk/package.json
> +    "@types/jest": "^27.0.2",
Thanks!

2021-10-22 16:49 UTC, jusiskin approved these changes

2021-10-22 17:46 UTC, ddneilson requested changes
Looks like there's still one more CI issue on the `yarn build` step:
```
aws-rfdk: $ cdk-build
aws-rfdk: warning JSII6: A "peerDependency" on "constructs" at "^3.3.69" means you should take a "devDependency" on "constructs" at "3.3.69" (found "^3.3.69")"
```

2021-10-22 17:52 UTC, ddneilson commented
> Looks like there's still one more CI issue on the `yarn build` step:
> 
> ```
> aws-rfdk: $ cdk-build
> aws-rfdk: warning JSII6: A "peerDependency" on "constructs" at "^3.3.69" me
> ```

Discussed off-line. We'll have to accept this warning.

2021-10-22 17:52 UTC, ddneilson approved these changes

2021-10-22 17:53 UTC, merged