chore: Add information on Security Considerations to constructs
aws/aws-rfdk pull request #80
Opened 2020-08-25 21:54 UTC by ddneilson

This is adding information on security considerations that customers should take into account when using the RFDK constructs. These are concrete recommendations, rather than security posture-type information.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-08-26 14:17 UTC, grbartel approved these changes

2020-08-26 17:17 UTC, jusiskin requested changes
This will be great for RFDK users. Just some minor additional considerations I think would be beneficial to add.

2020-08-27 15:14 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/health-monitor.ts
> + *   ability to modify or execute this Lambda.
That seems a little out-there to me. Probably not necessary

2020-08-27 15:27 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/mongodb-instance.ts
> + * ------------------------
Re: Backup -- it's in the docstring for this construct: "it is recommended that you set up a backup schedule for this volume."

I agree about adding a call-out about securing the EBS volume. Added for the next revision.

2020-08-27 15:27 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/staticip-server.ts
> + * ------------------------
Yeah, that would be a good idea.

2020-08-27 17:03 UTC, ddneilson commented on packages/aws-rfdk/lib/core/lib/x509-certificate.ts
> + * ------------------------
Absolutely. I can't believe that I missed that!

2020-08-27 17:16 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/lib/repository.ts
> + * ------------------------
Yup. Not sure how I missed mentioning that...

2020-08-27 17:33 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/lib/usage-based-licensing.ts
> + *   Futhermore, you should restrict that access to only the product(s) that those workers require when deploying this construct.
It doesn't actually impact the UBL credits -- those are a different mechanism that does not involve the software deployed by this construct. Ultiimately, the risk is piracy. I think what's here is sufficient.

2020-08-27 17:39 UTC, ddneilson commented on packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts
> + * ------------------------
I added something on patching. I'm not sure if it's worth mentioning that the instance has unrestricted access to Deadline. That kind of seems obvious

2020-08-27 17:45 UTC, ddneilson commented
I need to rebuild this PR. The switch to public repo severed the link between this and my repo.

2020-08-27 17:45 UTC, closed without merging